### ISSUE TITLE
fix tests, and mock js-ipfs-api

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-redux-bundle#11]
We don't need the tests to start a real ipfs instance to check that we do the right thing. Use https://github.com/nock/nock to mock out the required response to keep the tests fast and not dependent on the dev not running an api.

Of note we're testing in jest in a node process, so are tests are drifting away from how we expect this module to be used. I'm less bothered about that than I am about having tests for all the logic that this module performs, and not having the test runs be affected by my local set up.

**Comment by olizilla** [comment]
Ok, i'm going to have a go at this. shout if you're already working on it @hacdias

**Comment by hacdias** [comment]
@olizilla don't worry. I haven't started it yet
