### ISSUE TITLE
Refactor to use ipfs-provider internally

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-redux-bundle#40]
ipfs-provider is a light framework for getting IPFS API based on custom fallback logic.
We should avoid having two codebases that do the same thing and:

- switch `ipfs-redux-bundle` to be a think wrapper on top of `ipfs-provider`
- do not define `ipfs-http-client` version as a dependency, but use one provided by  user of this library 
  (for example, webui should define what version of `ipfs-http-client` should be used, and bumping that version should not require new release of `ipfs-redux-bundle`)

Ref. https://github.com/ipfs-shipyard/ipfs-provider

**Comment by Gozala** [comment]
How about we just make this library take ipfs node (instance or a client) and leave it up to users to provide it via ipfs-provider or any other means ?

**Comment by lidel** [comment]
I believe only webui used this library,  let's continue with deprecation plan in https://github.com/ipfs-shipyard/ipfs-redux-bundle/issues/42
